version: '3.1'

services:
  backend:
    container_name: marble-backend
    build:
      context: .
      args:
        - DATABASE_URL=$DATABASE_URL
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/apps/backend/logs
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
    networks:
      - marble-network
  postgresql:
    container_name: marble-postgresql
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env.postgresql
    networks:
      - marble-network
  redis:
    container_name: marble-redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - marble-network

networks:
    marble-network:
